# Generated by Django 5.1.7 on 2025-03-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorPays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
